### PR TITLE
home page layout updates and toolkit addition

### PR DESCRIPTION
**Pull request by akstuhl**
Updates the home page layout to place all main content into two columns: Lab (3/5 width) and Forum (2/5 width). The lab column includes a hero-featured project designated with the "lab_feature" category as well as the three most recent projects to have the "feature" flag enabled. Below these, it includes an analogous row of toolkit items, for which temporary posts have been created using content from http://mel.hofstra.edu/tool-kit.html. The forum column includes a hero-featured DREx item, with blog posts laid out sequentially in the column below.

### CODE REVIEW

**Review by jamiefolsom — COMMENTED** [review]
Hi Andy, this looks good so far -- how quick would it be to spin up a gh pages site to share with John et al?

I've got your branch running locally, and it's looking good. Couple of thoughts.

I think John's idea might have been to have the two columns just contain a stack of items, like this:

Lab | Forum
------------ | -------------
|Project one | DREx '17| 
|Tool one | DREx '16| 
|Special Collection One | Blog post| 
|This takes up two columns | Tweet, etc| 

But we should let them see the page, and ask that question.

**Comment by akstuhl** [comment]
@jamiefolsom could you check this repo's settings and enable gh pages if possible? I think if that's turned on, we can start using performant-software.github.io/drc as the staging site (I'll merge PRs into the gh-pages branch after initial code review)

**Comment by jamiefolsom** [comment]
Yes, the gh-pages branch is enabled. Forgot that's how that worked. I've checked out this PR, and it looks fine to me code-wise -- only question is whether we got the design concept correct, so if you would, take a couple of screenshots of the new home page design, and shoot them over to John and Ethna, with copy to me, asking if that work, or if they have requested changes, that would be great.

**Comment by jamiefolsom** [comment]
Disregard that screenshot idea -- the live staging site is a better way for them to check it out, so let's use that. Thanks!

**Pull request merged**
